import math
import numpy as np
from PIL import Image
import glob

"""
Trims images generated by blender to 500 x 500 that is a target for the 
model that is developed and adds them to a separate folder

For now hard coded for the initial input images from blender
"""

def trim_render_im(im_input_path, output_folder, window_size = 500):
    im_input = Image.open(im_input_path)
    im_input = np.asarray(im_input)
    # Loop over 4 subimages and save each separately
    crop_start_X = math.floor(im_input.shape[1]/2-window_size)
    crop_start_Y = math.floor(im_input.shape[0]/2-window_size)
    for i in range(2):
        for j in range(2):
            im_cropped = \
                im_input[
                crop_start_Y+window_size*j:crop_start_Y+window_size*(j+1),
                crop_start_X+window_size*i:crop_start_X+window_size*(i+1)]
            im = Image.fromarray(im_cropped, mode='L')
            path = output_folder+f"im_{i*2+j}.tiff"
            path = generate_output_name(output_folder)
            im.save(path)        
            
def generate_output_name(output_folder):
    # Check how many files are already in the output_folder
    files = glob.glob(output_folder + "\\im_*.tiff")
    new_im_num = len(files) + 1
    path = output_folder + f"\\im_{new_im_num}.tiff"
    return path
        
        
    

